# EDA - Pokemon Legendary Classifier

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Reading our clean pokemon dataset
df_pokemon = pd.read_csv(r"..\..\Data_Scientist_Training\Pokemon-Legendary-Classifier\datasets\pokemon_cleaned.csv")

In [6]:
# Checking out our dataset
df_pokemon.head(3)

,pokedex_number,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,Total Stats,is_legendary
0,1,Bulbasaur,grass,poison,45,49,49,65,65,45,318,0
1,2,Ivysaur,grass,poison,60,62,63,80,80,60,405,0
2,3,Venusaur,grass,poison,80,100,123,122,120,80,625,0

### Perform Exploring Data - EDA Technique

There are two common techniques to perform EDA: exploring and visualizing. In the exploration phase, we filter, group, and sort our data to summarize it and build a clearer understanding of what we are working with.

Keep in mind that the goal of EDA is to examine our data from multiple angles; uncovering patterns, relationships, and insights along the way. For example, we can explore how our data is distributed between normal and legendary Pokémon

In [10]:
# Grouping by pokemon type and finding average stats
df_pokemon.groupby(['type1'])[['attack', 'defense', 'speed']].agg('mean')

              attack     defense      speed
type1
bug        69.000000   69.873239  63.408451
dark       87.793103   70.517241  75.310345
dragon    106.407407   86.259259  76.111111
electric   70.820513   61.820513  85.410256
fairy      62.111111   68.166667  53.666667
fighting   99.178571   66.392857  64.285714
fire       81.500000   67.788462  73.346154
flying     66.666667   65.000000  99.666667
ghost      72.740741   79.518519  58.333333
grass      73.769231   70.871795  59.025641
ground     93.677419   82.741935  60.612903
ice        73.304348   71.913043  62.739130
normal     75.262136   59.252427  69.621359
poison     72.656250   70.031250  64.187500
psychic    65.566038   69.264151  75.150943
rock       90.666667   96.266667  57.422222
steel      93.083333  120.208333  56.583333
water      73.307018   73.482456  63.921053