# EDA - Pokemon Legendary Classifier

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Reading our clean pokemon dataset
df_pokemon = pd.read_csv(r"..\..\Data_Scientist_Training\Pokemon-Legendary-Classifier\datasets\pokemon_cleaned.csv")

In [3]:
# Checking out our dataset
df_pokemon.head(3)

,pokedex_number,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,Total Stats,is_legendary
0,1,Bulbasaur,grass,poison,45,49,49,65,65,45,318,0
1,2,Ivysaur,grass,poison,60,62,63,80,80,60,405,0
2,3,Venusaur,grass,poison,80,100,123,122,120,80,625,0

In [4]:
# Checking out the shape of our dataset
df_pokemon.shape

(797, 12)

## Perform Exploring Data - EDA Technique

There are two common techniques to perform EDA: exploring and visualizing. In the exploration phase, we filter, group, and sort our data to summarize it and build a clearer understanding of what we are working with.

Keep in mind that the goal of EDA is to examine our data from multiple angles; uncovering patterns, relationships, and insights along the way. For example, we can explore how our data is distributed between normal and legendary Pokémon

In [5]:
# Getting an statistical overview from our dataset
df_pokemon.describe()

,pokedex_number,hp,attack,defense,sp_attack,sp_defense,speed,Total Stats,is_legendary
count,797.000000,797.000000,797.000000,797.000000,797.000000,797.000000,797.000000,797.000000,797.000000
mean,401.943538,68.890841,77.721455,72.841907,71.431619,70.953576,66.360100,428.199498,0.087829
std,231.523934,26.594042,32.078151,30.684856,32.376040,27.949553,28.910268,119.194824,0.283224
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,180.000000,0.000000
25%,201.000000,50.000000,55.000000,50.000000,46.000000,50.000000,45.000000,320.000000,0.000000
50%,403.000000,65.000000,75.000000,70.000000,65.000000,66.000000,65.000000,435.000000,0.000000
75%,602.000000,80.000000,100.000000,90.000000,92.000000,90.000000,85.000000,505.000000,0.000000
max,801.000000,255.000000,185.000000,230.000000,194.000000,230.000000,180.000000,780.000000,1.000000

### Filtering Pokemon by stats, type and legendary record

Legendary Pokémon tend to have higher stats, so we will filter Pokémon with a total stat sum greater than 500 and check which ones are legendary.

Additionally, we'll review the types for each Pokémon. Some legendary Pokémon tend to have Psychic or Dragon as their primary type, and often feature dual typing.

In [7]:
# Filtering Pokemon whose stats are greater than 500
stats_mask = df_pokemon['Total Stats'] > 500

filtered_pokemon = df_pokemon[stats_mask]

In [ ]:
# Checking out legendary pokemons and its stats
filtered_pokemon[filtered_pokemon['is_legendary'] == 1]

,pokedex_number,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,Total Stats,is_legendary
142,144,Articuno,ice,flying,90,85,100,95,125,85,580,1
143,145,Zapdos,electric,flying,90,90,85,125,90,100,580,1
144,146,Moltres,fire,flying,90,100,90,125,85,90,580,1
148,150,Mewtwo,psychic,NaN,106,150,70,194,120,140,780,1
149,151,Mew,psychic,NaN,100,100,100,100,100,100,600,1
...,...,...,...,...,...,...,...,...,...,...,...,...
792,797,Celesteela,steel,flying,97,101,103,107,101,61,570,1
793,798,Kartana,grass,steel,59,181,131,59,31,109,570,1
794,799,Guzzlord,dark,dragon,223,101,53,97,53,43,570,1
795,800,Necrozma,psychic,NaN,97,107,101,127,89,79,600,1
796,801,Magearna,steel,fairy,80,95,115,130,115,65,600,1

In [17]:
# Filter by pokemon whose second type is null
filtered_pokemon[filtered_pokemon['type2'].isna()]

,pokedex_number,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,Total Stats,is_legendary
8,9,Blastoise,water,NaN,79,103,120,135,115,78,630,0
58,59,Arcanine,fire,NaN,90,110,80,100,80,95,555,0
64,65,Alakazam,psychic,NaN,55,50,65,175,105,150,600,0
67,68,Machamp,fighting,NaN,90,130,80,65,85,55,505,0
113,115,Kangaskhan,normal,NaN,105,125,100,60,100,100,590,0
...,...,...,...,...,...,...,...,...,...,...,...,...
758,763,Tsareena,grass,NaN,72,120,98,50,98,72,510,0
767,772,Type: Null,normal,NaN,95,95,95,95,95,59,534,0
768,773,Silvally,normal,NaN,95,95,95,95,95,95,570,0
791,796,Xurkitree,electric,NaN,83,89,71,173,71,83,570,1
795,800,Necrozma,psychic,NaN,97,107,101,127,89,79,600,1

In [21]:
type1_mask = (filtered_pokemon['type1'] == 'psychic') | (filtered_pokemon['type1'] == 'dragon')

filtered_pokemon[type1_mask]

,pokedex_number,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,Total Stats,is_legendary
64,65,Alakazam,psychic,NaN,55,50,65,175,105,150,600,0
147,149,Dragonite,dragon,flying,91,134,95,100,100,80,600,0
148,150,Mewtwo,psychic,NaN,106,150,70,194,120,140,780,1
149,151,Mew,psychic,NaN,100,100,100,100,100,100,600,1
194,196,Espeon,psychic,NaN,65,65,60,130,95,110,525,0
245,249,Lugia,psychic,flying,106,90,130,90,154,110,680,1
247,251,Celebi,psychic,grass,100,100,100,100,100,100,600,1
278,282,Gardevoir,psychic,fairy,68,85,65,165,135,100,618,0
329,334,Altaria,dragon,flying,75,110,110,110,105,80,590,0
368,373,Salamence,dragon,flying,95,145,130,120,90,120,700,0
375,380,Latias,dragon,psychic,80,100,120,140,150,110,700,1
376,381,Latios,dragon,psychic,80,130,100,160,120,110,700,1
379,384,Rayquaza,dragon,flying,105,180,100,180,100,115,780,1
381,386,Deoxys,psychic,NaN,50,95,90,95,90,180,600,1
440,445,Garchomp,dragon,ground,108,170,115,120,95,92,700,0
470,475,Gallade,psychic,fighting,68,165,95,65,115,110,618,0
475,480,Uxie,psychic,NaN,75,75,130,75,130,95,580,1
476,481,Mesprit,psychic,NaN,80,105,105,105,105,80,580,1
477,482,Azelf,psychic,NaN,75,125,70,125,70,115,580,1
483,488,Cresselia,psychic,NaN,120,70,120,75,130,85,600,1
489,494,Victini,psychic,fire,100,100,100,100,100,100,600,1
607,612,Haxorus,dragon,NaN,76,147,90,60,70,97,540,0
638,643,Reshiram,dragon,fire,100,120,100,150,120,90,680,1
639,644,Zekrom,dragon,electric,100,150,120,120,100,90,680,1
641,646,Kyurem,dragon,ice,125,120,90,170,100,95,700,1
701,706,Goodra,dragon,NaN,90,100,70,110,150,80,600,0
713,718,Zygarde,dragon,ground,216,100,121,91,95,85,708,1
715,720,Hoopa,psychic,ghost,80,160,60,170,130,80,680,1
779,784,Kommo-o,dragon,fighting,75,110,125,100,105,85,600,0
781,786,Tapu Lele,psychic,fairy,70,85,75,130,115,95,570,1
786,791,Solgaleo,psychic,steel,137,137,107,113,89,97,680,1
787,792,Lunala,psychic,ghost,137,113,89,137,107,97,680,1
795,800,Necrozma,psychic,NaN,97,107,101,127,89,79,600,1

Based on the filtering operations performed previously, we found that not all legendary Pokémon have a total stat sum greater than 500. Some of the filtered Pokémon are actually final evolutions, such as Blastoise and Alakazam.

Additionally, there is a total of 68 legendary Pokémon, which we'll need to distribute across our sets for ML training. We also confirmed that most legendaries have Psychic or Dragon as their primary type, a useful insight that will support our classifier.

### Sorting Pokemon by stats